// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: silo/status/v1/status.proto

package statusv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NodeState mirrors the SWIM membership states.
type NodeState int32

const (
	NodeState_NODE_STATE_UNSPECIFIED NodeState = 0
	NodeState_NODE_STATE_ALIVE       NodeState = 1
	NodeState_NODE_STATE_SUSPECT     NodeState = 2
	NodeState_NODE_STATE_DEAD        NodeState = 3
	NodeState_NODE_STATE_LEFT        NodeState = 4
)

// Enum value maps for NodeState.
var (
	NodeState_name = map[int32]string{
		0: "NODE_STATE_UNSPECIFIED",
		1: "NODE_STATE_ALIVE",
		2: "NODE_STATE_SUSPECT",
		3: "NODE_STATE_DEAD",
		4: "NODE_STATE_LEFT",
	}
	NodeState_value = map[string]int32{
		"NODE_STATE_UNSPECIFIED": 0,
		"NODE_STATE_ALIVE":       1,
		"NODE_STATE_SUSPECT":     2,
		"NODE_STATE_DEAD":        3,
		"NODE_STATE_LEFT":        4,
	}
)

func (x NodeState) Enum() *NodeState {
	p := new(NodeState)
	*p = x
	return p
}

func (x NodeState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeState) Descriptor() protoreflect.EnumDescriptor {
	return file_silo_status_v1_status_proto_enumTypes[0].Descriptor()
}

func (NodeState) Type() protoreflect.EnumType {
	return &file_silo_status_v1_status_proto_enumTypes[0]
}

func (x NodeState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeState.Descriptor instead.
func (NodeState) EnumDescriptor() ([]byte, []int) {
	return file_silo_status_v1_status_proto_rawDescGZIP(), []int{0}
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_silo_status_v1_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_status_v1_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_silo_status_v1_status_proto_rawDescGZIP(), []int{0}
}

// NodeStatus is one member as the responding node currently sees it.
type NodeStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GossipAddress string                 `protobuf:"bytes,2,opt,name=gossip_address,json=gossipAddress,proto3" json:"gossip_address,omitempty"`
	DataAddress   string                 `protobuf:"bytes,3,opt,name=data_address,json=dataAddress,proto3" json:"data_address,omitempty"`
	State         NodeState              `protobuf:"varint,4,opt,name=state,proto3,enum=silo.status.v1.NodeState" json:"state,omitempty"`
	Incarnation   uint64                 `protobuf:"varint,5,opt,name=incarnation,proto3" json:"incarnation,omitempty"`
	// last_change_unix is the epoch-seconds of this node's last state transition;
	// the CLI renders it as an age ("down for 2m").
	LastChangeUnix int64 `protobuf:"varint,6,opt,name=last_change_unix,json=lastChangeUnix,proto3" json:"last_change_unix,omitempty"`
	// capacity_bytes and used_bytes are the node's advertised backing-store size
	// and usage (zero until the node has advertised them over gossip).
	CapacityBytes int64 `protobuf:"varint,7,opt,name=capacity_bytes,json=capacityBytes,proto3" json:"capacity_bytes,omitempty"`
	UsedBytes     int64 `protobuf:"varint,8,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStatus) Reset() {
	*x = NodeStatus{}
	mi := &file_silo_status_v1_status_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatus) ProtoMessage() {}

func (x *NodeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_silo_status_v1_status_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatus.ProtoReflect.Descriptor instead.
func (*NodeStatus) Descriptor() ([]byte, []int) {
	return file_silo_status_v1_status_proto_rawDescGZIP(), []int{1}
}

func (x *NodeStatus) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodeStatus) GetGossipAddress() string {
	if x != nil {
		return x.GossipAddress
	}
	return ""
}

func (x *NodeStatus) GetDataAddress() string {
	if x != nil {
		return x.DataAddress
	}
	return ""
}

func (x *NodeStatus) GetState() NodeState {
	if x != nil {
		return x.State
	}
	return NodeState_NODE_STATE_UNSPECIFIED
}

func (x *NodeStatus) GetIncarnation() uint64 {
	if x != nil {
		return x.Incarnation
	}
	return 0
}

func (x *NodeStatus) GetLastChangeUnix() int64 {
	if x != nil {
		return x.LastChangeUnix
	}
	return 0
}

func (x *NodeStatus) GetCapacityBytes() int64 {
	if x != nil {
		return x.CapacityBytes
	}
	return 0
}

func (x *NodeStatus) GetUsedBytes() int64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

// StorageStatus is the responding node's local backing storage.
type StorageStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DataDir        string                 `protobuf:"bytes,1,opt,name=data_dir,json=dataDir,proto3" json:"data_dir,omitempty"`
	CapacityBytes  int64                  `protobuf:"varint,2,opt,name=capacity_bytes,json=capacityBytes,proto3" json:"capacity_bytes,omitempty"`
	UsedBytes      int64                  `protobuf:"varint,3,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`
	AvailableBytes int64                  `protobuf:"varint,4,opt,name=available_bytes,json=availableBytes,proto3" json:"available_bytes,omitempty"`
	ChunkCount     int64                  `protobuf:"varint,5,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StorageStatus) Reset() {
	*x = StorageStatus{}
	mi := &file_silo_status_v1_status_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageStatus) ProtoMessage() {}

func (x *StorageStatus) ProtoReflect() protoreflect.Message {
	mi := &file_silo_status_v1_status_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageStatus.ProtoReflect.Descriptor instead.
func (*StorageStatus) Descriptor() ([]byte, []int) {
	return file_silo_status_v1_status_proto_rawDescGZIP(), []int{2}
}

func (x *StorageStatus) GetDataDir() string {
	if x != nil {
		return x.DataDir
	}
	return ""
}

func (x *StorageStatus) GetCapacityBytes() int64 {
	if x != nil {
		return x.CapacityBytes
	}
	return 0
}

func (x *StorageStatus) GetUsedBytes() int64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *StorageStatus) GetAvailableBytes() int64 {
	if x != nil {
		return x.AvailableBytes
	}
	return 0
}

func (x *StorageStatus) GetChunkCount() int64 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

type GetStatusResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RespondingNodeId string                 `protobuf:"bytes,1,opt,name=responding_node_id,json=respondingNodeId,proto3" json:"responding_node_id,omitempty"`
	Version          string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Nodes            []*NodeStatus          `protobuf:"bytes,3,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Storage          *StorageStatus         `protobuf:"bytes,4,opt,name=storage,proto3" json:"storage,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_silo_status_v1_status_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_status_v1_status_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_silo_status_v1_status_proto_rawDescGZIP(), []int{3}
}

func (x *GetStatusResponse) GetRespondingNodeId() string {
	if x != nil {
		return x.RespondingNodeId
	}
	return ""
}

func (x *GetStatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetStatusResponse) GetNodes() []*NodeStatus {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *GetStatusResponse) GetStorage() *StorageStatus {
	if x != nil {
		return x.Storage
	}
	return nil
}

var File_silo_status_v1_status_proto protoreflect.FileDescriptor

const file_silo_status_v1_status_proto_rawDesc = "" +
	"\n" +
	"\x1bsilo/status/v1/status.proto\x12\x0esilo.status.v1\"\x12\n" +
	"\x10GetStatusRequest\"\xa9\x02\n" +
	"\n" +
	"NodeStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0egossip_address\x18\x02 \x01(\tR\rgossipAddress\x12!\n" +
	"\fdata_address\x18\x03 \x01(\tR\vdataAddress\x12/\n" +
	"\x05state\x18\x04 \x01(\x0e2\x19.silo.status.v1.NodeStateR\x05state\x12 \n" +
	"\vincarnation\x18\x05 \x01(\x04R\vincarnation\x12(\n" +
	"\x10last_change_unix\x18\x06 \x01(\x03R\x0elastChangeUnix\x12%\n" +
	"\x0ecapacity_bytes\x18\a \x01(\x03R\rcapacityBytes\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\b \x01(\x03R\tusedBytes\"\xba\x01\n" +
	"\rStorageStatus\x12\x19\n" +
	"\bdata_dir\x18\x01 \x01(\tR\adataDir\x12%\n" +
	"\x0ecapacity_bytes\x18\x02 \x01(\x03R\rcapacityBytes\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x03 \x01(\x03R\tusedBytes\x12'\n" +
	"\x0favailable_bytes\x18\x04 \x01(\x03R\x0eavailableBytes\x12\x1f\n" +
	"\vchunk_count\x18\x05 \x01(\x03R\n" +
	"chunkCount\"\xc6\x01\n" +
	"\x11GetStatusResponse\x12,\n" +
	"\x12responding_node_id\x18\x01 \x01(\tR\x10respondingNodeId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x120\n" +
	"\x05nodes\x18\x03 \x03(\v2\x1a.silo.status.v1.NodeStatusR\x05nodes\x127\n" +
	"\astorage\x18\x04 \x01(\v2\x1d.silo.status.v1.StorageStatusR\astorage*\x7f\n" +
	"\tNodeState\x12\x1a\n" +
	"\x16NODE_STATE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10NODE_STATE_ALIVE\x10\x01\x12\x16\n" +
	"\x12NODE_STATE_SUSPECT\x10\x02\x12\x13\n" +
	"\x0fNODE_STATE_DEAD\x10\x03\x12\x13\n" +
	"\x0fNODE_STATE_LEFT\x10\x042a\n" +
	"\rClusterStatus\x12P\n" +
	"\tGetStatus\x12 .silo.status.v1.GetStatusRequest\x1a!.silo.status.v1.GetStatusResponseB=Z;github.com/hyperized/silo/api/proto/silo/status/v1;statusv1b\x06proto3"

var (
	file_silo_status_v1_status_proto_rawDescOnce sync.Once
	file_silo_status_v1_status_proto_rawDescData []byte
)

func file_silo_status_v1_status_proto_rawDescGZIP() []byte {
	file_silo_status_v1_status_proto_rawDescOnce.Do(func() {
		file_silo_status_v1_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_silo_status_v1_status_proto_rawDesc), len(file_silo_status_v1_status_proto_rawDesc)))
	})
	return file_silo_status_v1_status_proto_rawDescData
}

var file_silo_status_v1_status_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_silo_status_v1_status_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_silo_status_v1_status_proto_goTypes = []any{
	(NodeState)(0),            // 0: silo.status.v1.NodeState
	(*GetStatusRequest)(nil),  // 1: silo.status.v1.GetStatusRequest
	(*NodeStatus)(nil),        // 2: silo.status.v1.NodeStatus
	(*StorageStatus)(nil),     // 3: silo.status.v1.StorageStatus
	(*GetStatusResponse)(nil), // 4: silo.status.v1.GetStatusResponse
}
var file_silo_status_v1_status_proto_depIdxs = []int32{
	0, // 0: silo.status.v1.NodeStatus.state:type_name -> silo.status.v1.NodeState
	2, // 1: silo.status.v1.GetStatusResponse.nodes:type_name -> silo.status.v1.NodeStatus
	3, // 2: silo.status.v1.GetStatusResponse.storage:type_name -> silo.status.v1.StorageStatus
	1, // 3: silo.status.v1.ClusterStatus.GetStatus:input_type -> silo.status.v1.GetStatusRequest
	4, // 4: silo.status.v1.ClusterStatus.GetStatus:output_type -> silo.status.v1.GetStatusResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_silo_status_v1_status_proto_init() }
func file_silo_status_v1_status_proto_init() {
	if File_silo_status_v1_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_silo_status_v1_status_proto_rawDesc), len(file_silo_status_v1_status_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_silo_status_v1_status_proto_goTypes,
		DependencyIndexes: file_silo_status_v1_status_proto_depIdxs,
		EnumInfos:         file_silo_status_v1_status_proto_enumTypes,
		MessageInfos:      file_silo_status_v1_status_proto_msgTypes,
	}.Build()
	File_silo_status_v1_status_proto = out.File
	file_silo_status_v1_status_proto_goTypes = nil
	file_silo_status_v1_status_proto_depIdxs = nil
}
