# silo — distributed storage system
# `make help` lists available targets. `make` (no args) brings up a local cluster.

SHELL := /bin/bash
.SHELLFLAGS := -eu -o pipefail -c

BIN := bin
COMPOSE := docker compose -f deploy/docker-compose.yml
COMPOSE_LOCAL := docker compose -f deploy/docker-compose-local.yml

VERSION ?= $(shell git describe --tags --always --dirty 2>/dev/null || echo dev)
LDFLAGS := -s -w -X main.version=$(VERSION)

GO_TEST_FLAGS ?= -race -timeout 60s
GO_PKGS := ./...

.PHONY: help up up-local down restart build test test-cover test-integration lint fmt vet clean logs status check proto
.DEFAULT_GOAL := up

help: ## Show this help and exit.
	@printf "silo — make targets\n\n"
	@awk -F ':[^#]*## ' '/^[a-zA-Z_-]+:[^#]*## / { printf "  \033[1m%-20s\033[0m %s\n", $$1, $$2 }' $(MAKEFILE_LIST)
	@printf "\nFirst run? Just type 'make'. It generates a dev key and boots a 3-node cluster.\n"

# --- Local cluster -----------------------------------------------------------

up: deploy/.env ## Build and start a 3-node silo cluster locally.
	@$(COMPOSE) up -d --build
	@printf "\nsilo is starting. Useful next steps:\n"
	@printf "  make status     check /healthz on every node\n"
	@printf "  make logs       follow logs across the cluster\n"
	@printf "  make down       stop everything (volumes removed)\n\n"
	@printf "Endpoints (give them ~10s to come up):\n"
	@printf "  http://localhost:7080/healthz   silo-a\n"
	@printf "  http://localhost:7081/healthz   silo-b\n"
	@printf "  http://localhost:7082/healthz   silo-c\n"
	@printf "  http://localhost:9090           prometheus\n"
	@printf "  http://localhost:%s           grafana (anonymous viewer; login admin/admin)\n" "$${SILO_GRAFANA_PORT:-3030}"

up-local: deploy/.env ## Run a single silod in the foreground (fast dev loop).
	@$(COMPOSE_LOCAL) up --build

down: ## Stop the cluster and remove its volumes.
	@$(COMPOSE) down -v

restart: down up ## Stop and restart the cluster.

status: ## Probe /healthz on every node and report.
	@printf "Probing cluster…\n"
	@for port in 7080 7081 7082; do \
	  body=$$(curl -sf --max-time 2 http://localhost:$$port/healthz 2>/dev/null || true); \
	  if [ -n "$$body" ]; then printf "  OK  port %s — %s\n" "$$port" "$$body"; \
	  else printf "  --  port %s — not ready yet (try again in a few seconds)\n" "$$port"; fi; \
	done

logs: ## Follow logs from all silo nodes.
	@$(COMPOSE) logs -f silo-a silo-b silo-c

deploy/.env:
	@printf "# Generated by 'make up' — never commit (see .gitignore).\n# To rotate, delete this file and re-run 'make up'.\nSILO_ENCRYPTION_KEY=%s\nSILO_LOG_LEVEL=info\nSILO_LOG_FORMAT=text\n" "$$(openssl rand -base64 32 | tr -d '\n')" > $@
	@printf "Generated deploy/.env with a fresh development encryption key.\n"

# --- Build & test ------------------------------------------------------------

build: ## Build all Go binaries into bin/.
	@mkdir -p $(BIN)
	@CGO_ENABLED=0 go build -ldflags "$(LDFLAGS)" -o $(BIN)/silod ./cmd/silod
	@CGO_ENABLED=0 go build -ldflags "$(LDFLAGS)" -o $(BIN)/siloctl ./cmd/siloctl
	@printf "Built %s/silod, %s/siloctl (%s)\n" "$(BIN)" "$(BIN)" "$(VERSION)"

test: ## Run unit tests.
	@go test $(GO_TEST_FLAGS) $(GO_PKGS)

test-cover: ## Run unit tests and print coverage (excludes generated code).
	@go test $(GO_TEST_FLAGS) -coverprofile=coverage.out -coverpkg=./internal/...,./cmd/...,./pkg/... $(GO_PKGS)
	@printf "\nOverall coverage: "
	@go tool cover -func=coverage.out | awk '/^total:/ {print $$3}'
	@printf "HTML report: \`go tool cover -html=coverage.out\`\n"

test-integration: ## Run integration tests (require docker, build-tag 'integration').
	@go test $(GO_TEST_FLAGS) -tags=integration ./test/integration/...

proto: ## Regenerate protobuf and gRPC code. Requires Docker; uses bufbuild/buf.
	@if ! docker info >/dev/null 2>&1; then \
	  printf "Docker is not running; start Docker Desktop or the docker daemon first.\nProto regeneration uses the bufbuild/buf image so you do not need protoc installed locally.\n" >&2; \
	  exit 1; \
	fi
	@docker run --rm \
	  -v "$(PWD):/work" \
	  -w /work \
	  --user "$$(id -u):$$(id -g)" \
	  -e HOME=/tmp \
	  bufbuild/buf:latest generate
	@printf "Regenerated *.pb.go under api/proto/. Commit the result.\n"

lint: ## Run golangci-lint (install if missing: https://golangci-lint.run/usage/install/).
	@if ! command -v golangci-lint >/dev/null 2>&1; then \
	  printf "golangci-lint is not installed.\nInstall it with:\n  brew install golangci-lint     (macOS)\n  https://golangci-lint.run/usage/install/  (everywhere else)\n" >&2; \
	  exit 1; \
	fi
	@golangci-lint run

fmt: ## Run gofmt on the entire repo.
	@gofmt -s -w .

vet: ## Run go vet.
	@go vet $(GO_PKGS)

check: fmt vet lint test ## Run formatters, linters, and tests.

# --- Housekeeping ------------------------------------------------------------

clean: ## Remove build artifacts and the generated .env.
	@rm -rf $(BIN) coverage.out
	@rm -f deploy/.env
	@printf "Removed bin/, coverage.out, deploy/.env\n"
