// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: silo/namespace/v1/namespace.proto

package namespacev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NamespaceStore_Mkdir_FullMethodName       = "/silo.namespace.v1.NamespaceStore/Mkdir"
	NamespaceStore_Touch_FullMethodName       = "/silo.namespace.v1.NamespaceStore/Touch"
	NamespaceStore_List_FullMethodName        = "/silo.namespace.v1.NamespaceStore/List"
	NamespaceStore_Remove_FullMethodName      = "/silo.namespace.v1.NamespaceStore/Remove"
	NamespaceStore_AppendChunk_FullMethodName = "/silo.namespace.v1.NamespaceStore/AppendChunk"
	NamespaceStore_Manifest_FullMethodName    = "/silo.namespace.v1.NamespaceStore/Manifest"
)

// NamespaceStoreClient is the client API for NamespaceStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NamespaceStore is silod's operator-facing view of the cluster's CRDT
// filesystem namespace. Mutations are local to the receiving node and
// converge to peers over gossip anti-entropy; reads resolve the receiving
// node's current replica.
type NamespaceStoreClient interface {
	Mkdir(ctx context.Context, in *MkdirRequest, opts ...grpc.CallOption) (*MkdirResponse, error)
	Touch(ctx context.Context, in *TouchRequest, opts ...grpc.CallOption) (*TouchResponse, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error)
	// AppendChunk records a chunk id in a file's manifest. Writers call this
	// after storing the chunk so a reader can later reassemble the file in
	// append (HLC) order.
	AppendChunk(ctx context.Context, in *AppendChunkRequest, opts ...grpc.CallOption) (*AppendChunkResponse, error)
	// Manifest returns a file's chunk ids in the order a reader concatenates
	// them to reconstruct the byte stream.
	Manifest(ctx context.Context, in *ManifestRequest, opts ...grpc.CallOption) (*ManifestResponse, error)
}

type namespaceStoreClient struct {
	cc grpc.ClientConnInterface
}

func NewNamespaceStoreClient(cc grpc.ClientConnInterface) NamespaceStoreClient {
	return &namespaceStoreClient{cc}
}

func (c *namespaceStoreClient) Mkdir(ctx context.Context, in *MkdirRequest, opts ...grpc.CallOption) (*MkdirResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MkdirResponse)
	err := c.cc.Invoke(ctx, NamespaceStore_Mkdir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *namespaceStoreClient) Touch(ctx context.Context, in *TouchRequest, opts ...grpc.CallOption) (*TouchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TouchResponse)
	err := c.cc.Invoke(ctx, NamespaceStore_Touch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *namespaceStoreClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, NamespaceStore_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *namespaceStoreClient) Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveResponse)
	err := c.cc.Invoke(ctx, NamespaceStore_Remove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *namespaceStoreClient) AppendChunk(ctx context.Context, in *AppendChunkRequest, opts ...grpc.CallOption) (*AppendChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppendChunkResponse)
	err := c.cc.Invoke(ctx, NamespaceStore_AppendChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *namespaceStoreClient) Manifest(ctx context.Context, in *ManifestRequest, opts ...grpc.CallOption) (*ManifestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ManifestResponse)
	err := c.cc.Invoke(ctx, NamespaceStore_Manifest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NamespaceStoreServer is the server API for NamespaceStore service.
// All implementations should embed UnimplementedNamespaceStoreServer
// for forward compatibility.
//
// NamespaceStore is silod's operator-facing view of the cluster's CRDT
// filesystem namespace. Mutations are local to the receiving node and
// converge to peers over gossip anti-entropy; reads resolve the receiving
// node's current replica.
type NamespaceStoreServer interface {
	Mkdir(context.Context, *MkdirRequest) (*MkdirResponse, error)
	Touch(context.Context, *TouchRequest) (*TouchResponse, error)
	List(context.Context, *ListRequest) (*ListResponse, error)
	Remove(context.Context, *RemoveRequest) (*RemoveResponse, error)
	// AppendChunk records a chunk id in a file's manifest. Writers call this
	// after storing the chunk so a reader can later reassemble the file in
	// append (HLC) order.
	AppendChunk(context.Context, *AppendChunkRequest) (*AppendChunkResponse, error)
	// Manifest returns a file's chunk ids in the order a reader concatenates
	// them to reconstruct the byte stream.
	Manifest(context.Context, *ManifestRequest) (*ManifestResponse, error)
}

// UnimplementedNamespaceStoreServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNamespaceStoreServer struct{}

func (UnimplementedNamespaceStoreServer) Mkdir(context.Context, *MkdirRequest) (*MkdirResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Mkdir not implemented")
}
func (UnimplementedNamespaceStoreServer) Touch(context.Context, *TouchRequest) (*TouchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Touch not implemented")
}
func (UnimplementedNamespaceStoreServer) List(context.Context, *ListRequest) (*ListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedNamespaceStoreServer) Remove(context.Context, *RemoveRequest) (*RemoveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Remove not implemented")
}
func (UnimplementedNamespaceStoreServer) AppendChunk(context.Context, *AppendChunkRequest) (*AppendChunkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AppendChunk not implemented")
}
func (UnimplementedNamespaceStoreServer) Manifest(context.Context, *ManifestRequest) (*ManifestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Manifest not implemented")
}
func (UnimplementedNamespaceStoreServer) testEmbeddedByValue() {}

// UnsafeNamespaceStoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NamespaceStoreServer will
// result in compilation errors.
type UnsafeNamespaceStoreServer interface {
	mustEmbedUnimplementedNamespaceStoreServer()
}

func RegisterNamespaceStoreServer(s grpc.ServiceRegistrar, srv NamespaceStoreServer) {
	// If the following call panics, it indicates UnimplementedNamespaceStoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NamespaceStore_ServiceDesc, srv)
}

func _NamespaceStore_Mkdir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MkdirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NamespaceStoreServer).Mkdir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NamespaceStore_Mkdir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NamespaceStoreServer).Mkdir(ctx, req.(*MkdirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NamespaceStore_Touch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TouchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NamespaceStoreServer).Touch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NamespaceStore_Touch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NamespaceStoreServer).Touch(ctx, req.(*TouchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NamespaceStore_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NamespaceStoreServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NamespaceStore_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NamespaceStoreServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NamespaceStore_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NamespaceStoreServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NamespaceStore_Remove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NamespaceStoreServer).Remove(ctx, req.(*RemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NamespaceStore_AppendChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NamespaceStoreServer).AppendChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NamespaceStore_AppendChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NamespaceStoreServer).AppendChunk(ctx, req.(*AppendChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NamespaceStore_Manifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManifestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NamespaceStoreServer).Manifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NamespaceStore_Manifest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NamespaceStoreServer).Manifest(ctx, req.(*ManifestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NamespaceStore_ServiceDesc is the grpc.ServiceDesc for NamespaceStore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NamespaceStore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "silo.namespace.v1.NamespaceStore",
	HandlerType: (*NamespaceStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Mkdir",
			Handler:    _NamespaceStore_Mkdir_Handler,
		},
		{
			MethodName: "Touch",
			Handler:    _NamespaceStore_Touch_Handler,
		},
		{
			MethodName: "List",
			Handler:    _NamespaceStore_List_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _NamespaceStore_Remove_Handler,
		},
		{
			MethodName: "AppendChunk",
			Handler:    _NamespaceStore_AppendChunk_Handler,
		},
		{
			MethodName: "Manifest",
			Handler:    _NamespaceStore_Manifest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "silo/namespace/v1/namespace.proto",
}
