// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: silo/namespace/v1/namespace.proto

package namespacev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EntryType distinguishes a directory from a file.
type EntryType int32

const (
	EntryType_ENTRY_TYPE_DIR  EntryType = 0
	EntryType_ENTRY_TYPE_FILE EntryType = 1
)

// Enum value maps for EntryType.
var (
	EntryType_name = map[int32]string{
		0: "ENTRY_TYPE_DIR",
		1: "ENTRY_TYPE_FILE",
	}
	EntryType_value = map[string]int32{
		"ENTRY_TYPE_DIR":  0,
		"ENTRY_TYPE_FILE": 1,
	}
)

func (x EntryType) Enum() *EntryType {
	p := new(EntryType)
	*p = x
	return p
}

func (x EntryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntryType) Descriptor() protoreflect.EnumDescriptor {
	return file_silo_namespace_v1_namespace_proto_enumTypes[0].Descriptor()
}

func (EntryType) Type() protoreflect.EnumType {
	return &file_silo_namespace_v1_namespace_proto_enumTypes[0]
}

func (x EntryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntryType.Descriptor instead.
func (EntryType) EnumDescriptor() ([]byte, []int) {
	return file_silo_namespace_v1_namespace_proto_rawDescGZIP(), []int{0}
}

type MkdirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirRequest) Reset() {
	*x = MkdirRequest{}
	mi := &file_silo_namespace_v1_namespace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirRequest) ProtoMessage() {}

func (x *MkdirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_namespace_v1_namespace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirRequest.ProtoReflect.Descriptor instead.
func (*MkdirRequest) Descriptor() ([]byte, []int) {
	return file_silo_namespace_v1_namespace_proto_rawDescGZIP(), []int{0}
}

func (x *MkdirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type MkdirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inode         string                 `protobuf:"bytes,1,opt,name=inode,proto3" json:"inode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirResponse) Reset() {
	*x = MkdirResponse{}
	mi := &file_silo_namespace_v1_namespace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirResponse) ProtoMessage() {}

func (x *MkdirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_namespace_v1_namespace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirResponse.ProtoReflect.Descriptor instead.
func (*MkdirResponse) Descriptor() ([]byte, []int) {
	return file_silo_namespace_v1_namespace_proto_rawDescGZIP(), []int{1}
}

func (x *MkdirResponse) GetInode() string {
	if x != nil {
		return x.Inode
	}
	return ""
}

type TouchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TouchRequest) Reset() {
	*x = TouchRequest{}
	mi := &file_silo_namespace_v1_namespace_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TouchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TouchRequest) ProtoMessage() {}

func (x *TouchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_namespace_v1_namespace_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TouchRequest.ProtoReflect.Descriptor instead.
func (*TouchRequest) Descriptor() ([]byte, []int) {
	return file_silo_namespace_v1_namespace_proto_rawDescGZIP(), []int{2}
}

func (x *TouchRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type TouchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inode         string                 `protobuf:"bytes,1,opt,name=inode,proto3" json:"inode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TouchResponse) Reset() {
	*x = TouchResponse{}
	mi := &file_silo_namespace_v1_namespace_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TouchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TouchResponse) ProtoMessage() {}

func (x *TouchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_namespace_v1_namespace_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TouchResponse.ProtoReflect.Descriptor instead.
func (*TouchResponse) Descriptor() ([]byte, []int) {
	return file_silo_namespace_v1_namespace_proto_rawDescGZIP(), []int{3}
}

func (x *TouchResponse) GetInode() string {
	if x != nil {
		return x.Inode
	}
	return ""
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_silo_namespace_v1_namespace_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_namespace_v1_namespace_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_silo_namespace_v1_namespace_proto_rawDescGZIP(), []int{4}
}

func (x *ListRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// Entry is one resolved child. When concurrent creates collided, the
// highest-HLC claim keeps the bare name and the others carry a
// ".conflict-<hlc>" name with conflict set.
type Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Inode         string                 `protobuf:"bytes,2,opt,name=inode,proto3" json:"inode,omitempty"`
	Type          EntryType              `protobuf:"varint,3,opt,name=type,proto3,enum=silo.namespace.v1.EntryType" json:"type,omitempty"`
	Conflict      bool                   `protobuf:"varint,4,opt,name=conflict,proto3" json:"conflict,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_silo_namespace_v1_namespace_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_silo_namespace_v1_namespace_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_silo_namespace_v1_namespace_proto_rawDescGZIP(), []int{5}
}

func (x *Entry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Entry) GetInode() string {
	if x != nil {
		return x.Inode
	}
	return ""
}

func (x *Entry) GetType() EntryType {
	if x != nil {
		return x.Type
	}
	return EntryType_ENTRY_TYPE_DIR
}

func (x *Entry) GetConflict() bool {
	if x != nil {
		return x.Conflict
	}
	return false
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*Entry               `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_silo_namespace_v1_namespace_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_namespace_v1_namespace_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_silo_namespace_v1_namespace_proto_rawDescGZIP(), []int{6}
}

func (x *ListResponse) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type RemoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRequest) Reset() {
	*x = RemoveRequest{}
	mi := &file_silo_namespace_v1_namespace_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRequest) ProtoMessage() {}

func (x *RemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_namespace_v1_namespace_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRequest.ProtoReflect.Descriptor instead.
func (*RemoveRequest) Descriptor() ([]byte, []int) {
	return file_silo_namespace_v1_namespace_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type RemoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveResponse) Reset() {
	*x = RemoveResponse{}
	mi := &file_silo_namespace_v1_namespace_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveResponse) ProtoMessage() {}

func (x *RemoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_namespace_v1_namespace_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveResponse.ProtoReflect.Descriptor instead.
func (*RemoveResponse) Descriptor() ([]byte, []int) {
	return file_silo_namespace_v1_namespace_proto_rawDescGZIP(), []int{8}
}

var File_silo_namespace_v1_namespace_proto protoreflect.FileDescriptor

const file_silo_namespace_v1_namespace_proto_rawDesc = "" +
	"\n" +
	"!silo/namespace/v1/namespace.proto\x12\x11silo.namespace.v1\"\"\n" +
	"\fMkdirRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"%\n" +
	"\rMkdirResponse\x12\x14\n" +
	"\x05inode\x18\x01 \x01(\tR\x05inode\"\"\n" +
	"\fTouchRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"%\n" +
	"\rTouchResponse\x12\x14\n" +
	"\x05inode\x18\x01 \x01(\tR\x05inode\"!\n" +
	"\vListRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\x7f\n" +
	"\x05Entry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05inode\x18\x02 \x01(\tR\x05inode\x120\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1c.silo.namespace.v1.EntryTypeR\x04type\x12\x1a\n" +
	"\bconflict\x18\x04 \x01(\bR\bconflict\"B\n" +
	"\fListResponse\x122\n" +
	"\aentries\x18\x01 \x03(\v2\x18.silo.namespace.v1.EntryR\aentries\"#\n" +
	"\rRemoveRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\x10\n" +
	"\x0eRemoveResponse*4\n" +
	"\tEntryType\x12\x12\n" +
	"\x0eENTRY_TYPE_DIR\x10\x00\x12\x13\n" +
	"\x0fENTRY_TYPE_FILE\x10\x012\xc0\x02\n" +
	"\x0eNamespaceStore\x12J\n" +
	"\x05Mkdir\x12\x1f.silo.namespace.v1.MkdirRequest\x1a .silo.namespace.v1.MkdirResponse\x12J\n" +
	"\x05Touch\x12\x1f.silo.namespace.v1.TouchRequest\x1a .silo.namespace.v1.TouchResponse\x12G\n" +
	"\x04List\x12\x1e.silo.namespace.v1.ListRequest\x1a\x1f.silo.namespace.v1.ListResponse\x12M\n" +
	"\x06Remove\x12 .silo.namespace.v1.RemoveRequest\x1a!.silo.namespace.v1.RemoveResponseBCZAgithub.com/hyperized/silo/api/proto/silo/namespace/v1;namespacev1b\x06proto3"

var (
	file_silo_namespace_v1_namespace_proto_rawDescOnce sync.Once
	file_silo_namespace_v1_namespace_proto_rawDescData []byte
)

func file_silo_namespace_v1_namespace_proto_rawDescGZIP() []byte {
	file_silo_namespace_v1_namespace_proto_rawDescOnce.Do(func() {
		file_silo_namespace_v1_namespace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_silo_namespace_v1_namespace_proto_rawDesc), len(file_silo_namespace_v1_namespace_proto_rawDesc)))
	})
	return file_silo_namespace_v1_namespace_proto_rawDescData
}

var file_silo_namespace_v1_namespace_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_silo_namespace_v1_namespace_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_silo_namespace_v1_namespace_proto_goTypes = []any{
	(EntryType)(0),         // 0: silo.namespace.v1.EntryType
	(*MkdirRequest)(nil),   // 1: silo.namespace.v1.MkdirRequest
	(*MkdirResponse)(nil),  // 2: silo.namespace.v1.MkdirResponse
	(*TouchRequest)(nil),   // 3: silo.namespace.v1.TouchRequest
	(*TouchResponse)(nil),  // 4: silo.namespace.v1.TouchResponse
	(*ListRequest)(nil),    // 5: silo.namespace.v1.ListRequest
	(*Entry)(nil),          // 6: silo.namespace.v1.Entry
	(*ListResponse)(nil),   // 7: silo.namespace.v1.ListResponse
	(*RemoveRequest)(nil),  // 8: silo.namespace.v1.RemoveRequest
	(*RemoveResponse)(nil), // 9: silo.namespace.v1.RemoveResponse
}
var file_silo_namespace_v1_namespace_proto_depIdxs = []int32{
	0, // 0: silo.namespace.v1.Entry.type:type_name -> silo.namespace.v1.EntryType
	6, // 1: silo.namespace.v1.ListResponse.entries:type_name -> silo.namespace.v1.Entry
	1, // 2: silo.namespace.v1.NamespaceStore.Mkdir:input_type -> silo.namespace.v1.MkdirRequest
	3, // 3: silo.namespace.v1.NamespaceStore.Touch:input_type -> silo.namespace.v1.TouchRequest
	5, // 4: silo.namespace.v1.NamespaceStore.List:input_type -> silo.namespace.v1.ListRequest
	8, // 5: silo.namespace.v1.NamespaceStore.Remove:input_type -> silo.namespace.v1.RemoveRequest
	2, // 6: silo.namespace.v1.NamespaceStore.Mkdir:output_type -> silo.namespace.v1.MkdirResponse
	4, // 7: silo.namespace.v1.NamespaceStore.Touch:output_type -> silo.namespace.v1.TouchResponse
	7, // 8: silo.namespace.v1.NamespaceStore.List:output_type -> silo.namespace.v1.ListResponse
	9, // 9: silo.namespace.v1.NamespaceStore.Remove:output_type -> silo.namespace.v1.RemoveResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_silo_namespace_v1_namespace_proto_init() }
func file_silo_namespace_v1_namespace_proto_init() {
	if File_silo_namespace_v1_namespace_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_silo_namespace_v1_namespace_proto_rawDesc), len(file_silo_namespace_v1_namespace_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_silo_namespace_v1_namespace_proto_goTypes,
		DependencyIndexes: file_silo_namespace_v1_namespace_proto_depIdxs,
		EnumInfos:         file_silo_namespace_v1_namespace_proto_enumTypes,
		MessageInfos:      file_silo_namespace_v1_namespace_proto_msgTypes,
	}.Build()
	File_silo_namespace_v1_namespace_proto = out.File
	file_silo_namespace_v1_namespace_proto_goTypes = nil
	file_silo_namespace_v1_namespace_proto_depIdxs = nil
}
