// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: silo/bootstrap/v1/bootstrap.proto

package bootstrapv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JoinRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// token: the plaintext join token the operator was handed when the
	// cluster came up. Server compares its sha256 against the token store
	// in constant time, refuses the request, and consumes the entry on
	// success (single-use tokens become invalid after this call).
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// principal identifies the human or system requesting the cert. Folded
	// into the issued certificate's CommonName so future audit logs can
	// attribute actions back to a person, not just to "some operator".
	// A sensible default is "<os-user>@<hostname>".
	Principal     string `protobuf:"bytes,2,opt,name=principal,proto3" json:"principal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_silo_bootstrap_v1_bootstrap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_bootstrap_v1_bootstrap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_silo_bootstrap_v1_bootstrap_proto_rawDescGZIP(), []int{0}
}

func (x *JoinRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *JoinRequest) GetPrincipal() string {
	if x != nil {
		return x.Principal
	}
	return ""
}

type JoinResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ca_cert_pem is the cluster CA the operator's siloctl should pin for
	// future mTLS connections.
	CaCertPem []byte `protobuf:"bytes,1,opt,name=ca_cert_pem,json=caCertPem,proto3" json:"ca_cert_pem,omitempty"`
	// client_cert_pem is a fresh certificate signed by the cluster CA,
	// valid for the lifetime configured on silod. The operator stores it
	// alongside ca_cert_pem and presents it on every subsequent RPC.
	ClientCertPem []byte `protobuf:"bytes,2,opt,name=client_cert_pem,json=clientCertPem,proto3" json:"client_cert_pem,omitempty"`
	// client_key_pem is the private key matching client_cert_pem. silod
	// returns it once; lose it and the operator must redeem a new token.
	ClientKeyPem []byte `protobuf:"bytes,3,opt,name=client_key_pem,json=clientKeyPem,proto3" json:"client_key_pem,omitempty"`
	// grpc_address tells the operator's siloctl where to send subsequent
	// chunk RPCs. The bootstrap listener is on a different port (and may
	// be on a different host:port pair entirely when one node fronts the
	// join API on behalf of the cluster), so this field carries the actual
	// mTLS gRPC endpoint operators should dial next. siloctl persists it
	// as default_grpc_server in its config.json.
	GrpcAddress   string `protobuf:"bytes,4,opt,name=grpc_address,json=grpcAddress,proto3" json:"grpc_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinResponse) Reset() {
	*x = JoinResponse{}
	mi := &file_silo_bootstrap_v1_bootstrap_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse) ProtoMessage() {}

func (x *JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_bootstrap_v1_bootstrap_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse.ProtoReflect.Descriptor instead.
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return file_silo_bootstrap_v1_bootstrap_proto_rawDescGZIP(), []int{1}
}

func (x *JoinResponse) GetCaCertPem() []byte {
	if x != nil {
		return x.CaCertPem
	}
	return nil
}

func (x *JoinResponse) GetClientCertPem() []byte {
	if x != nil {
		return x.ClientCertPem
	}
	return nil
}

func (x *JoinResponse) GetClientKeyPem() []byte {
	if x != nil {
		return x.ClientKeyPem
	}
	return nil
}

func (x *JoinResponse) GetGrpcAddress() string {
	if x != nil {
		return x.GrpcAddress
	}
	return ""
}

var File_silo_bootstrap_v1_bootstrap_proto protoreflect.FileDescriptor

const file_silo_bootstrap_v1_bootstrap_proto_rawDesc = "" +
	"\n" +
	"!silo/bootstrap/v1/bootstrap.proto\x12\x11silo.bootstrap.v1\"A\n" +
	"\vJoinRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1c\n" +
	"\tprincipal\x18\x02 \x01(\tR\tprincipal\"\x9f\x01\n" +
	"\fJoinResponse\x12\x1e\n" +
	"\vca_cert_pem\x18\x01 \x01(\fR\tcaCertPem\x12&\n" +
	"\x0fclient_cert_pem\x18\x02 \x01(\fR\rclientCertPem\x12$\n" +
	"\x0eclient_key_pem\x18\x03 \x01(\fR\fclientKeyPem\x12!\n" +
	"\fgrpc_address\x18\x04 \x01(\tR\vgrpcAddress2T\n" +
	"\tBootstrap\x12G\n" +
	"\x04Join\x12\x1e.silo.bootstrap.v1.JoinRequest\x1a\x1f.silo.bootstrap.v1.JoinResponseBCZAgithub.com/hyperized/silo/api/proto/silo/bootstrap/v1;bootstrapv1b\x06proto3"

var (
	file_silo_bootstrap_v1_bootstrap_proto_rawDescOnce sync.Once
	file_silo_bootstrap_v1_bootstrap_proto_rawDescData []byte
)

func file_silo_bootstrap_v1_bootstrap_proto_rawDescGZIP() []byte {
	file_silo_bootstrap_v1_bootstrap_proto_rawDescOnce.Do(func() {
		file_silo_bootstrap_v1_bootstrap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_silo_bootstrap_v1_bootstrap_proto_rawDesc), len(file_silo_bootstrap_v1_bootstrap_proto_rawDesc)))
	})
	return file_silo_bootstrap_v1_bootstrap_proto_rawDescData
}

var file_silo_bootstrap_v1_bootstrap_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_silo_bootstrap_v1_bootstrap_proto_goTypes = []any{
	(*JoinRequest)(nil),  // 0: silo.bootstrap.v1.JoinRequest
	(*JoinResponse)(nil), // 1: silo.bootstrap.v1.JoinResponse
}
var file_silo_bootstrap_v1_bootstrap_proto_depIdxs = []int32{
	0, // 0: silo.bootstrap.v1.Bootstrap.Join:input_type -> silo.bootstrap.v1.JoinRequest
	1, // 1: silo.bootstrap.v1.Bootstrap.Join:output_type -> silo.bootstrap.v1.JoinResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_silo_bootstrap_v1_bootstrap_proto_init() }
func file_silo_bootstrap_v1_bootstrap_proto_init() {
	if File_silo_bootstrap_v1_bootstrap_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_silo_bootstrap_v1_bootstrap_proto_rawDesc), len(file_silo_bootstrap_v1_bootstrap_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_silo_bootstrap_v1_bootstrap_proto_goTypes,
		DependencyIndexes: file_silo_bootstrap_v1_bootstrap_proto_depIdxs,
		MessageInfos:      file_silo_bootstrap_v1_bootstrap_proto_msgTypes,
	}.Build()
	File_silo_bootstrap_v1_bootstrap_proto = out.File
	file_silo_bootstrap_v1_bootstrap_proto_goTypes = nil
	file_silo_bootstrap_v1_bootstrap_proto_depIdxs = nil
}
