// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: silo/bootstrap/v1/bootstrap.proto

package bootstrapv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Bootstrap_Join_FullMethodName = "/silo.bootstrap.v1.Bootstrap/Join"
)

// BootstrapClient is the client API for Bootstrap service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Bootstrap is the one silod service that runs without mutual TLS.
// Operators use it once to redeem a join token for a client certificate
// signed by the cluster CA; from then on every other silod surface is
// mTLS-only. The listener is intentionally separate from the main gRPC
// server (different port, different tls.Config) so the trust boundary
// is obvious from the wire even before any token has been exchanged.
type BootstrapClient interface {
	// Join exchanges a one-time token for a freshly-signed client
	// certificate plus the cluster CA cert. The server uses the principal
	// as the certificate subject so operator-attributed audit logs are
	// possible once authentication is in place.
	Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error)
}

type bootstrapClient struct {
	cc grpc.ClientConnInterface
}

func NewBootstrapClient(cc grpc.ClientConnInterface) BootstrapClient {
	return &bootstrapClient{cc}
}

func (c *bootstrapClient) Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinResponse)
	err := c.cc.Invoke(ctx, Bootstrap_Join_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BootstrapServer is the server API for Bootstrap service.
// All implementations should embed UnimplementedBootstrapServer
// for forward compatibility.
//
// Bootstrap is the one silod service that runs without mutual TLS.
// Operators use it once to redeem a join token for a client certificate
// signed by the cluster CA; from then on every other silod surface is
// mTLS-only. The listener is intentionally separate from the main gRPC
// server (different port, different tls.Config) so the trust boundary
// is obvious from the wire even before any token has been exchanged.
type BootstrapServer interface {
	// Join exchanges a one-time token for a freshly-signed client
	// certificate plus the cluster CA cert. The server uses the principal
	// as the certificate subject so operator-attributed audit logs are
	// possible once authentication is in place.
	Join(context.Context, *JoinRequest) (*JoinResponse, error)
}

// UnimplementedBootstrapServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBootstrapServer struct{}

func (UnimplementedBootstrapServer) Join(context.Context, *JoinRequest) (*JoinResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Join not implemented")
}
func (UnimplementedBootstrapServer) testEmbeddedByValue() {}

// UnsafeBootstrapServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BootstrapServer will
// result in compilation errors.
type UnsafeBootstrapServer interface {
	mustEmbedUnimplementedBootstrapServer()
}

func RegisterBootstrapServer(s grpc.ServiceRegistrar, srv BootstrapServer) {
	// If the following call panics, it indicates UnimplementedBootstrapServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Bootstrap_ServiceDesc, srv)
}

func _Bootstrap_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BootstrapServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bootstrap_Join_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BootstrapServer).Join(ctx, req.(*JoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Bootstrap_ServiceDesc is the grpc.ServiceDesc for Bootstrap service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Bootstrap_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "silo.bootstrap.v1.Bootstrap",
	HandlerType: (*BootstrapServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Join",
			Handler:    _Bootstrap_Join_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "silo/bootstrap/v1/bootstrap.proto",
}
