// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: silo/node/v1/node.proto

package nodev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeAdmin_Drain_FullMethodName = "/silo.node.v1.NodeAdmin/Drain"
)

// NodeAdminClient is the client API for NodeAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NodeAdmin is silod's operator-facing node-lifecycle surface. Unlike the
// read-only ClusterStatus service, these RPCs mutate the node, so they are kept
// separate.
type NodeAdminClient interface {
	// Drain marks the receiving node as having left the cluster and announces it
	// over gossip, so peers route placement around it and re-replicate the chunks
	// it held onto survivors. The node keeps running and serving its chunks until
	// it is removed — drain is not shutdown. Watch silo_replication_shortfall_chunks
	// fall to zero before removing the node.
	Drain(ctx context.Context, in *DrainRequest, opts ...grpc.CallOption) (*DrainResponse, error)
}

type nodeAdminClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeAdminClient(cc grpc.ClientConnInterface) NodeAdminClient {
	return &nodeAdminClient{cc}
}

func (c *nodeAdminClient) Drain(ctx context.Context, in *DrainRequest, opts ...grpc.CallOption) (*DrainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DrainResponse)
	err := c.cc.Invoke(ctx, NodeAdmin_Drain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeAdminServer is the server API for NodeAdmin service.
// All implementations should embed UnimplementedNodeAdminServer
// for forward compatibility.
//
// NodeAdmin is silod's operator-facing node-lifecycle surface. Unlike the
// read-only ClusterStatus service, these RPCs mutate the node, so they are kept
// separate.
type NodeAdminServer interface {
	// Drain marks the receiving node as having left the cluster and announces it
	// over gossip, so peers route placement around it and re-replicate the chunks
	// it held onto survivors. The node keeps running and serving its chunks until
	// it is removed — drain is not shutdown. Watch silo_replication_shortfall_chunks
	// fall to zero before removing the node.
	Drain(context.Context, *DrainRequest) (*DrainResponse, error)
}

// UnimplementedNodeAdminServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeAdminServer struct{}

func (UnimplementedNodeAdminServer) Drain(context.Context, *DrainRequest) (*DrainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Drain not implemented")
}
func (UnimplementedNodeAdminServer) testEmbeddedByValue() {}

// UnsafeNodeAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeAdminServer will
// result in compilation errors.
type UnsafeNodeAdminServer interface {
	mustEmbedUnimplementedNodeAdminServer()
}

func RegisterNodeAdminServer(s grpc.ServiceRegistrar, srv NodeAdminServer) {
	// If the following call panics, it indicates UnimplementedNodeAdminServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeAdmin_ServiceDesc, srv)
}

func _NodeAdmin_Drain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DrainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAdminServer).Drain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAdmin_Drain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAdminServer).Drain(ctx, req.(*DrainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeAdmin_ServiceDesc is the grpc.ServiceDesc for NodeAdmin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeAdmin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "silo.node.v1.NodeAdmin",
	HandlerType: (*NodeAdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Drain",
			Handler:    _NodeAdmin_Drain_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "silo/node/v1/node.proto",
}
