// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: silo/node/v1/node.proto

package nodev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DrainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrainRequest) Reset() {
	*x = DrainRequest{}
	mi := &file_silo_node_v1_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainRequest) ProtoMessage() {}

func (x *DrainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_node_v1_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainRequest.ProtoReflect.Descriptor instead.
func (*DrainRequest) Descriptor() ([]byte, []int) {
	return file_silo_node_v1_node_proto_rawDescGZIP(), []int{0}
}

type DrainResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// node_id is the drained node's id.
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// announced is true when this call transitioned the node to Left; false when
	// it was already draining (the call is idempotent).
	Announced     bool `protobuf:"varint,2,opt,name=announced,proto3" json:"announced,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrainResponse) Reset() {
	*x = DrainResponse{}
	mi := &file_silo_node_v1_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainResponse) ProtoMessage() {}

func (x *DrainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_node_v1_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainResponse.ProtoReflect.Descriptor instead.
func (*DrainResponse) Descriptor() ([]byte, []int) {
	return file_silo_node_v1_node_proto_rawDescGZIP(), []int{1}
}

func (x *DrainResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *DrainResponse) GetAnnounced() bool {
	if x != nil {
		return x.Announced
	}
	return false
}

var File_silo_node_v1_node_proto protoreflect.FileDescriptor

const file_silo_node_v1_node_proto_rawDesc = "" +
	"\n" +
	"\x17silo/node/v1/node.proto\x12\fsilo.node.v1\"\x0e\n" +
	"\fDrainRequest\"F\n" +
	"\rDrainResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1c\n" +
	"\tannounced\x18\x02 \x01(\bR\tannounced2M\n" +
	"\tNodeAdmin\x12@\n" +
	"\x05Drain\x12\x1a.silo.node.v1.DrainRequest\x1a\x1b.silo.node.v1.DrainResponseB9Z7github.com/hyperized/silo/api/proto/silo/node/v1;nodev1b\x06proto3"

var (
	file_silo_node_v1_node_proto_rawDescOnce sync.Once
	file_silo_node_v1_node_proto_rawDescData []byte
)

func file_silo_node_v1_node_proto_rawDescGZIP() []byte {
	file_silo_node_v1_node_proto_rawDescOnce.Do(func() {
		file_silo_node_v1_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_silo_node_v1_node_proto_rawDesc), len(file_silo_node_v1_node_proto_rawDesc)))
	})
	return file_silo_node_v1_node_proto_rawDescData
}

var file_silo_node_v1_node_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_silo_node_v1_node_proto_goTypes = []any{
	(*DrainRequest)(nil),  // 0: silo.node.v1.DrainRequest
	(*DrainResponse)(nil), // 1: silo.node.v1.DrainResponse
}
var file_silo_node_v1_node_proto_depIdxs = []int32{
	0, // 0: silo.node.v1.NodeAdmin.Drain:input_type -> silo.node.v1.DrainRequest
	1, // 1: silo.node.v1.NodeAdmin.Drain:output_type -> silo.node.v1.DrainResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_silo_node_v1_node_proto_init() }
func file_silo_node_v1_node_proto_init() {
	if File_silo_node_v1_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_silo_node_v1_node_proto_rawDesc), len(file_silo_node_v1_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_silo_node_v1_node_proto_goTypes,
		DependencyIndexes: file_silo_node_v1_node_proto_depIdxs,
		MessageInfos:      file_silo_node_v1_node_proto_msgTypes,
	}.Build()
	File_silo_node_v1_node_proto = out.File
	file_silo_node_v1_node_proto_goTypes = nil
	file_silo_node_v1_node_proto_depIdxs = nil
}
