global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: silo
    static_configs:
      - targets:
          - silo-a:7080
          - silo-b:7080
          - silo-c:7080
        labels:
          cluster: silo-dev
    relabel_configs:
      - source_labels: [__address__]
        regex: '([^:]+):.*'
        target_label: node
        replacement: '$1'
