// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: silo/chunk/v1/chunk.proto

package chunkv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChunkStore_Put_FullMethodName    = "/silo.chunk.v1.ChunkStore/Put"
	ChunkStore_Get_FullMethodName    = "/silo.chunk.v1.ChunkStore/Get"
	ChunkStore_Delete_FullMethodName = "/silo.chunk.v1.ChunkStore/Delete"
	ChunkStore_Stat_FullMethodName   = "/silo.chunk.v1.ChunkStore/Stat"
)

// ChunkStoreClient is the client API for ChunkStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ChunkStore is the silod-side chunk RPC surface. Put and Get are
// streaming because chunk payloads can exceed the default 4 MiB gRPC
// message limit and we do not want to twist operators into configuring
// max-message-size on both ends.
type ChunkStoreClient interface {
	Put(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PutRequest, PutResponse], error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetResponse], error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	Stat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*StatResponse, error)
}

type chunkStoreClient struct {
	cc grpc.ClientConnInterface
}

func NewChunkStoreClient(cc grpc.ClientConnInterface) ChunkStoreClient {
	return &chunkStoreClient{cc}
}

func (c *chunkStoreClient) Put(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PutRequest, PutResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChunkStore_ServiceDesc.Streams[0], ChunkStore_Put_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PutRequest, PutResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChunkStore_PutClient = grpc.ClientStreamingClient[PutRequest, PutResponse]

func (c *chunkStoreClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChunkStore_ServiceDesc.Streams[1], ChunkStore_Get_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetRequest, GetResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChunkStore_GetClient = grpc.ServerStreamingClient[GetResponse]

func (c *chunkStoreClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, ChunkStore_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chunkStoreClient) Stat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*StatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatResponse)
	err := c.cc.Invoke(ctx, ChunkStore_Stat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChunkStoreServer is the server API for ChunkStore service.
// All implementations should embed UnimplementedChunkStoreServer
// for forward compatibility.
//
// ChunkStore is the silod-side chunk RPC surface. Put and Get are
// streaming because chunk payloads can exceed the default 4 MiB gRPC
// message limit and we do not want to twist operators into configuring
// max-message-size on both ends.
type ChunkStoreServer interface {
	Put(grpc.ClientStreamingServer[PutRequest, PutResponse]) error
	Get(*GetRequest, grpc.ServerStreamingServer[GetResponse]) error
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	Stat(context.Context, *StatRequest) (*StatResponse, error)
}

// UnimplementedChunkStoreServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChunkStoreServer struct{}

func (UnimplementedChunkStoreServer) Put(grpc.ClientStreamingServer[PutRequest, PutResponse]) error {
	return status.Error(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedChunkStoreServer) Get(*GetRequest, grpc.ServerStreamingServer[GetResponse]) error {
	return status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedChunkStoreServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedChunkStoreServer) Stat(context.Context, *StatRequest) (*StatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stat not implemented")
}
func (UnimplementedChunkStoreServer) testEmbeddedByValue() {}

// UnsafeChunkStoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChunkStoreServer will
// result in compilation errors.
type UnsafeChunkStoreServer interface {
	mustEmbedUnimplementedChunkStoreServer()
}

func RegisterChunkStoreServer(s grpc.ServiceRegistrar, srv ChunkStoreServer) {
	// If the following call panics, it indicates UnimplementedChunkStoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChunkStore_ServiceDesc, srv)
}

func _ChunkStore_Put_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChunkStoreServer).Put(&grpc.GenericServerStream[PutRequest, PutResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChunkStore_PutServer = grpc.ClientStreamingServer[PutRequest, PutResponse]

func _ChunkStore_Get_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChunkStoreServer).Get(m, &grpc.GenericServerStream[GetRequest, GetResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChunkStore_GetServer = grpc.ServerStreamingServer[GetResponse]

func _ChunkStore_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkStoreServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChunkStore_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkStoreServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChunkStore_Stat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkStoreServer).Stat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChunkStore_Stat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkStoreServer).Stat(ctx, req.(*StatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChunkStore_ServiceDesc is the grpc.ServiceDesc for ChunkStore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChunkStore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "silo.chunk.v1.ChunkStore",
	HandlerType: (*ChunkStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Delete",
			Handler:    _ChunkStore_Delete_Handler,
		},
		{
			MethodName: "Stat",
			Handler:    _ChunkStore_Stat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Put",
			Handler:       _ChunkStore_Put_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Get",
			Handler:       _ChunkStore_Get_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "silo/chunk/v1/chunk.proto",
}
