// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: silo/chunk/v1/chunk.proto

package chunkv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ChunkInfo carries plaintext and on-disk sizes so callers can reason
// about encryption overhead without a follow-up Stat.
type ChunkInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	PlainBytes    int64                  `protobuf:"varint,2,opt,name=plain_bytes,json=plainBytes,proto3" json:"plain_bytes,omitempty"`
	StoredBytes   int64                  `protobuf:"varint,3,opt,name=stored_bytes,json=storedBytes,proto3" json:"stored_bytes,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkInfo) Reset() {
	*x = ChunkInfo{}
	mi := &file_silo_chunk_v1_chunk_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkInfo) ProtoMessage() {}

func (x *ChunkInfo) ProtoReflect() protoreflect.Message {
	mi := &file_silo_chunk_v1_chunk_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkInfo.ProtoReflect.Descriptor instead.
func (*ChunkInfo) Descriptor() ([]byte, []int) {
	return file_silo_chunk_v1_chunk_proto_rawDescGZIP(), []int{0}
}

func (x *ChunkInfo) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *ChunkInfo) GetPlainBytes() int64 {
	if x != nil {
		return x.PlainBytes
	}
	return 0
}

func (x *ChunkInfo) GetStoredBytes() int64 {
	if x != nil {
		return x.StoredBytes
	}
	return 0
}

func (x *ChunkInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// PutRequest: first frame carries the header, subsequent frames carry
// data. Splitting the oneof keeps the schema honest — the chunk id is
// announced exactly once, before any bytes.
type PutRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*PutRequest_Header
	//	*PutRequest_Data
	Body          isPutRequest_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_silo_chunk_v1_chunk_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_chunk_v1_chunk_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_silo_chunk_v1_chunk_proto_rawDescGZIP(), []int{1}
}

func (x *PutRequest) GetBody() isPutRequest_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *PutRequest) GetHeader() *PutHeader {
	if x != nil {
		if x, ok := x.Body.(*PutRequest_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *PutRequest) GetData() []byte {
	if x != nil {
		if x, ok := x.Body.(*PutRequest_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isPutRequest_Body interface {
	isPutRequest_Body()
}

type PutRequest_Header struct {
	Header *PutHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type PutRequest_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*PutRequest_Header) isPutRequest_Body() {}

func (*PutRequest_Data) isPutRequest_Body() {}

type PutHeader struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ChunkId string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	// replica marks a peer-to-peer replica write: the receiving node stores
	// the chunk on its local disk only and does NOT coordinate further
	// replication. The replication coordinator sets this when fanning a
	// chunk out to a peer; a normal client write leaves it false so the
	// receiving node coordinates placement across the ring.
	Replica       bool `protobuf:"varint,2,opt,name=replica,proto3" json:"replica,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutHeader) Reset() {
	*x = PutHeader{}
	mi := &file_silo_chunk_v1_chunk_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutHeader) ProtoMessage() {}

func (x *PutHeader) ProtoReflect() protoreflect.Message {
	mi := &file_silo_chunk_v1_chunk_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutHeader.ProtoReflect.Descriptor instead.
func (*PutHeader) Descriptor() ([]byte, []int) {
	return file_silo_chunk_v1_chunk_proto_rawDescGZIP(), []int{2}
}

func (x *PutHeader) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *PutHeader) GetReplica() bool {
	if x != nil {
		return x.Replica
	}
	return false
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *ChunkInfo             `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_silo_chunk_v1_chunk_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_chunk_v1_chunk_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_silo_chunk_v1_chunk_proto_rawDescGZIP(), []int{3}
}

func (x *PutResponse) GetInfo() *ChunkInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type GetRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ChunkId string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	// local_only restricts the read to the receiving node's local store and
	// suppresses the ring fall-back. The replication coordinator sets this
	// when fetching a replica from a specific peer so the fetch cannot
	// bounce back across the ring; a normal client read leaves it false.
	LocalOnly     bool `protobuf:"varint,2,opt,name=local_only,json=localOnly,proto3" json:"local_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_silo_chunk_v1_chunk_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_chunk_v1_chunk_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_silo_chunk_v1_chunk_proto_rawDescGZIP(), []int{4}
}

func (x *GetRequest) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *GetRequest) GetLocalOnly() bool {
	if x != nil {
		return x.LocalOnly
	}
	return false
}

// GetResponse: server sends one info frame first, then any number of
// data frames. Clients should treat receipt of info as "the chunk
// exists and is decrypting"; bytes follow.
type GetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*GetResponse_Info
	//	*GetResponse_Data
	Body          isGetResponse_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_silo_chunk_v1_chunk_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_chunk_v1_chunk_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_silo_chunk_v1_chunk_proto_rawDescGZIP(), []int{5}
}

func (x *GetResponse) GetBody() isGetResponse_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *GetResponse) GetInfo() *ChunkInfo {
	if x != nil {
		if x, ok := x.Body.(*GetResponse_Info); ok {
			return x.Info
		}
	}
	return nil
}

func (x *GetResponse) GetData() []byte {
	if x != nil {
		if x, ok := x.Body.(*GetResponse_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isGetResponse_Body interface {
	isGetResponse_Body()
}

type GetResponse_Info struct {
	Info *ChunkInfo `protobuf:"bytes,1,opt,name=info,proto3,oneof"`
}

type GetResponse_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*GetResponse_Info) isGetResponse_Body() {}

func (*GetResponse_Data) isGetResponse_Body() {}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_silo_chunk_v1_chunk_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_chunk_v1_chunk_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_silo_chunk_v1_chunk_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteRequest) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_silo_chunk_v1_chunk_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_chunk_v1_chunk_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_silo_chunk_v1_chunk_proto_rawDescGZIP(), []int{7}
}

type StatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatRequest) Reset() {
	*x = StatRequest{}
	mi := &file_silo_chunk_v1_chunk_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRequest) ProtoMessage() {}

func (x *StatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_chunk_v1_chunk_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatRequest.ProtoReflect.Descriptor instead.
func (*StatRequest) Descriptor() ([]byte, []int) {
	return file_silo_chunk_v1_chunk_proto_rawDescGZIP(), []int{8}
}

func (x *StatRequest) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

type StatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *ChunkInfo             `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatResponse) Reset() {
	*x = StatResponse{}
	mi := &file_silo_chunk_v1_chunk_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatResponse) ProtoMessage() {}

func (x *StatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_chunk_v1_chunk_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatResponse.ProtoReflect.Descriptor instead.
func (*StatResponse) Descriptor() ([]byte, []int) {
	return file_silo_chunk_v1_chunk_proto_rawDescGZIP(), []int{9}
}

func (x *StatResponse) GetInfo() *ChunkInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

var File_silo_chunk_v1_chunk_proto protoreflect.FileDescriptor

const file_silo_chunk_v1_chunk_proto_rawDesc = "" +
	"\n" +
	"\x19silo/chunk/v1/chunk.proto\x12\rsilo.chunk.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa5\x01\n" +
	"\tChunkInfo\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x1f\n" +
	"\vplain_bytes\x18\x02 \x01(\x03R\n" +
	"plainBytes\x12!\n" +
	"\fstored_bytes\x18\x03 \x01(\x03R\vstoredBytes\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"^\n" +
	"\n" +
	"PutRequest\x122\n" +
	"\x06header\x18\x01 \x01(\v2\x18.silo.chunk.v1.PutHeaderH\x00R\x06header\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\x06\n" +
	"\x04body\"@\n" +
	"\tPutHeader\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x18\n" +
	"\areplica\x18\x02 \x01(\bR\areplica\";\n" +
	"\vPutResponse\x12,\n" +
	"\x04info\x18\x01 \x01(\v2\x18.silo.chunk.v1.ChunkInfoR\x04info\"F\n" +
	"\n" +
	"GetRequest\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x1d\n" +
	"\n" +
	"local_only\x18\x02 \x01(\bR\tlocalOnly\"[\n" +
	"\vGetResponse\x12.\n" +
	"\x04info\x18\x01 \x01(\v2\x18.silo.chunk.v1.ChunkInfoH\x00R\x04info\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\x06\n" +
	"\x04body\"*\n" +
	"\rDeleteRequest\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\"\x10\n" +
	"\x0eDeleteResponse\"(\n" +
	"\vStatRequest\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\"<\n" +
	"\fStatResponse\x12,\n" +
	"\x04info\x18\x01 \x01(\v2\x18.silo.chunk.v1.ChunkInfoR\x04info2\x94\x02\n" +
	"\n" +
	"ChunkStore\x12>\n" +
	"\x03Put\x12\x19.silo.chunk.v1.PutRequest\x1a\x1a.silo.chunk.v1.PutResponse(\x01\x12>\n" +
	"\x03Get\x12\x19.silo.chunk.v1.GetRequest\x1a\x1a.silo.chunk.v1.GetResponse0\x01\x12E\n" +
	"\x06Delete\x12\x1c.silo.chunk.v1.DeleteRequest\x1a\x1d.silo.chunk.v1.DeleteResponse\x12?\n" +
	"\x04Stat\x12\x1a.silo.chunk.v1.StatRequest\x1a\x1b.silo.chunk.v1.StatResponseB;Z9github.com/hyperized/silo/api/proto/silo/chunk/v1;chunkv1b\x06proto3"

var (
	file_silo_chunk_v1_chunk_proto_rawDescOnce sync.Once
	file_silo_chunk_v1_chunk_proto_rawDescData []byte
)

func file_silo_chunk_v1_chunk_proto_rawDescGZIP() []byte {
	file_silo_chunk_v1_chunk_proto_rawDescOnce.Do(func() {
		file_silo_chunk_v1_chunk_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_silo_chunk_v1_chunk_proto_rawDesc), len(file_silo_chunk_v1_chunk_proto_rawDesc)))
	})
	return file_silo_chunk_v1_chunk_proto_rawDescData
}

var file_silo_chunk_v1_chunk_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_silo_chunk_v1_chunk_proto_goTypes = []any{
	(*ChunkInfo)(nil),             // 0: silo.chunk.v1.ChunkInfo
	(*PutRequest)(nil),            // 1: silo.chunk.v1.PutRequest
	(*PutHeader)(nil),             // 2: silo.chunk.v1.PutHeader
	(*PutResponse)(nil),           // 3: silo.chunk.v1.PutResponse
	(*GetRequest)(nil),            // 4: silo.chunk.v1.GetRequest
	(*GetResponse)(nil),           // 5: silo.chunk.v1.GetResponse
	(*DeleteRequest)(nil),         // 6: silo.chunk.v1.DeleteRequest
	(*DeleteResponse)(nil),        // 7: silo.chunk.v1.DeleteResponse
	(*StatRequest)(nil),           // 8: silo.chunk.v1.StatRequest
	(*StatResponse)(nil),          // 9: silo.chunk.v1.StatResponse
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_silo_chunk_v1_chunk_proto_depIdxs = []int32{
	10, // 0: silo.chunk.v1.ChunkInfo.created_at:type_name -> google.protobuf.Timestamp
	2,  // 1: silo.chunk.v1.PutRequest.header:type_name -> silo.chunk.v1.PutHeader
	0,  // 2: silo.chunk.v1.PutResponse.info:type_name -> silo.chunk.v1.ChunkInfo
	0,  // 3: silo.chunk.v1.GetResponse.info:type_name -> silo.chunk.v1.ChunkInfo
	0,  // 4: silo.chunk.v1.StatResponse.info:type_name -> silo.chunk.v1.ChunkInfo
	1,  // 5: silo.chunk.v1.ChunkStore.Put:input_type -> silo.chunk.v1.PutRequest
	4,  // 6: silo.chunk.v1.ChunkStore.Get:input_type -> silo.chunk.v1.GetRequest
	6,  // 7: silo.chunk.v1.ChunkStore.Delete:input_type -> silo.chunk.v1.DeleteRequest
	8,  // 8: silo.chunk.v1.ChunkStore.Stat:input_type -> silo.chunk.v1.StatRequest
	3,  // 9: silo.chunk.v1.ChunkStore.Put:output_type -> silo.chunk.v1.PutResponse
	5,  // 10: silo.chunk.v1.ChunkStore.Get:output_type -> silo.chunk.v1.GetResponse
	7,  // 11: silo.chunk.v1.ChunkStore.Delete:output_type -> silo.chunk.v1.DeleteResponse
	9,  // 12: silo.chunk.v1.ChunkStore.Stat:output_type -> silo.chunk.v1.StatResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_silo_chunk_v1_chunk_proto_init() }
func file_silo_chunk_v1_chunk_proto_init() {
	if File_silo_chunk_v1_chunk_proto != nil {
		return
	}
	file_silo_chunk_v1_chunk_proto_msgTypes[1].OneofWrappers = []any{
		(*PutRequest_Header)(nil),
		(*PutRequest_Data)(nil),
	}
	file_silo_chunk_v1_chunk_proto_msgTypes[5].OneofWrappers = []any{
		(*GetResponse_Info)(nil),
		(*GetResponse_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_silo_chunk_v1_chunk_proto_rawDesc), len(file_silo_chunk_v1_chunk_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_silo_chunk_v1_chunk_proto_goTypes,
		DependencyIndexes: file_silo_chunk_v1_chunk_proto_depIdxs,
		MessageInfos:      file_silo_chunk_v1_chunk_proto_msgTypes,
	}.Build()
	File_silo_chunk_v1_chunk_proto = out.File
	file_silo_chunk_v1_chunk_proto_goTypes = nil
	file_silo_chunk_v1_chunk_proto_depIdxs = nil
}
