// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: silo/extent/v1/extent.proto

package extentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Hlc is silo's hybrid logical clock timestamp on the wire.
type Hlc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wall          int64                  `protobuf:"varint,1,opt,name=wall,proto3" json:"wall,omitempty"`
	Logical       uint32                 `protobuf:"varint,2,opt,name=logical,proto3" json:"logical,omitempty"`
	Node          string                 `protobuf:"bytes,3,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hlc) Reset() {
	*x = Hlc{}
	mi := &file_silo_extent_v1_extent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hlc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hlc) ProtoMessage() {}

func (x *Hlc) ProtoReflect() protoreflect.Message {
	mi := &file_silo_extent_v1_extent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hlc.ProtoReflect.Descriptor instead.
func (*Hlc) Descriptor() ([]byte, []int) {
	return file_silo_extent_v1_extent_proto_rawDescGZIP(), []int{0}
}

func (x *Hlc) GetWall() int64 {
	if x != nil {
		return x.Wall
	}
	return 0
}

func (x *Hlc) GetLogical() uint32 {
	if x != nil {
		return x.Logical
	}
	return 0
}

func (x *Hlc) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

// ExtentEntry binds one extent index to the chunk that backs it, stamped with
// the HLC of the write so replicas resolve it last-writer-wins.
type ExtentEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint64                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	ChunkId       string                 `protobuf:"bytes,2,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Ts            *Hlc                   `protobuf:"bytes,3,opt,name=ts,proto3" json:"ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtentEntry) Reset() {
	*x = ExtentEntry{}
	mi := &file_silo_extent_v1_extent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtentEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtentEntry) ProtoMessage() {}

func (x *ExtentEntry) ProtoReflect() protoreflect.Message {
	mi := &file_silo_extent_v1_extent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtentEntry.ProtoReflect.Descriptor instead.
func (*ExtentEntry) Descriptor() ([]byte, []int) {
	return file_silo_extent_v1_extent_proto_rawDescGZIP(), []int{1}
}

func (x *ExtentEntry) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ExtentEntry) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *ExtentEntry) GetTs() *Hlc {
	if x != nil {
		return x.Ts
	}
	return nil
}

type ApplyRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	VolumeId string                 `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	Entries  []*ExtentEntry         `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	// replica marks a peer-to-peer replica write: the receiving node applies to
	// its local store only and does NOT fan out further. The coordinator sets it
	// when replicating to the volume's replica set; a coordinator-side apply
	// leaves it false (it does the fan-out itself).
	Replica bool `protobuf:"varint,3,opt,name=replica,proto3" json:"replica,omitempty"`
	// ensure, with no entries, creates an empty map for the volume so a
	// freshly-created volume is established on its replica set before any write.
	Ensure        bool `protobuf:"varint,4,opt,name=ensure,proto3" json:"ensure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyRequest) Reset() {
	*x = ApplyRequest{}
	mi := &file_silo_extent_v1_extent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRequest) ProtoMessage() {}

func (x *ApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_extent_v1_extent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRequest.ProtoReflect.Descriptor instead.
func (*ApplyRequest) Descriptor() ([]byte, []int) {
	return file_silo_extent_v1_extent_proto_rawDescGZIP(), []int{2}
}

func (x *ApplyRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *ApplyRequest) GetEntries() []*ExtentEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ApplyRequest) GetReplica() bool {
	if x != nil {
		return x.Replica
	}
	return false
}

func (x *ApplyRequest) GetEnsure() bool {
	if x != nil {
		return x.Ensure
	}
	return false
}

type ApplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyResponse) Reset() {
	*x = ApplyResponse{}
	mi := &file_silo_extent_v1_extent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyResponse) ProtoMessage() {}

func (x *ApplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_extent_v1_extent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyResponse.ProtoReflect.Descriptor instead.
func (*ApplyResponse) Descriptor() ([]byte, []int) {
	return file_silo_extent_v1_extent_proto_rawDescGZIP(), []int{3}
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeId      string                 `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_silo_extent_v1_extent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_extent_v1_extent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_silo_extent_v1_extent_proto_rawDescGZIP(), []int{4}
}

func (x *GetRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*ExtentEntry         `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_silo_extent_v1_extent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_extent_v1_extent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_silo_extent_v1_extent_proto_rawDescGZIP(), []int{5}
}

func (x *GetResponse) GetEntries() []*ExtentEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type StatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeId      string                 `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatRequest) Reset() {
	*x = StatRequest{}
	mi := &file_silo_extent_v1_extent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRequest) ProtoMessage() {}

func (x *StatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_extent_v1_extent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatRequest.ProtoReflect.Descriptor instead.
func (*StatRequest) Descriptor() ([]byte, []int) {
	return file_silo_extent_v1_extent_proto_rawDescGZIP(), []int{6}
}

func (x *StatRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

type StatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Has           bool                   `protobuf:"varint,1,opt,name=has,proto3" json:"has,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatResponse) Reset() {
	*x = StatResponse{}
	mi := &file_silo_extent_v1_extent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatResponse) ProtoMessage() {}

func (x *StatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_extent_v1_extent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatResponse.ProtoReflect.Descriptor instead.
func (*StatResponse) Descriptor() ([]byte, []int) {
	return file_silo_extent_v1_extent_proto_rawDescGZIP(), []int{7}
}

func (x *StatResponse) GetHas() bool {
	if x != nil {
		return x.Has
	}
	return false
}

func (x *StatResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_silo_extent_v1_extent_proto protoreflect.FileDescriptor

const file_silo_extent_v1_extent_proto_rawDesc = "" +
	"\n" +
	"\x1bsilo/extent/v1/extent.proto\x12\x0esilo.extent.v1\"G\n" +
	"\x03Hlc\x12\x12\n" +
	"\x04wall\x18\x01 \x01(\x03R\x04wall\x12\x18\n" +
	"\alogical\x18\x02 \x01(\rR\alogical\x12\x12\n" +
	"\x04node\x18\x03 \x01(\tR\x04node\"c\n" +
	"\vExtentEntry\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x04R\x05index\x12\x19\n" +
	"\bchunk_id\x18\x02 \x01(\tR\achunkId\x12#\n" +
	"\x02ts\x18\x03 \x01(\v2\x13.silo.extent.v1.HlcR\x02ts\"\x94\x01\n" +
	"\fApplyRequest\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\x125\n" +
	"\aentries\x18\x02 \x03(\v2\x1b.silo.extent.v1.ExtentEntryR\aentries\x12\x18\n" +
	"\areplica\x18\x03 \x01(\bR\areplica\x12\x16\n" +
	"\x06ensure\x18\x04 \x01(\bR\x06ensure\"\x0f\n" +
	"\rApplyResponse\")\n" +
	"\n" +
	"GetRequest\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\"D\n" +
	"\vGetResponse\x125\n" +
	"\aentries\x18\x01 \x03(\v2\x1b.silo.extent.v1.ExtentEntryR\aentries\"*\n" +
	"\vStatRequest\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\"6\n" +
	"\fStatResponse\x12\x10\n" +
	"\x03has\x18\x01 \x01(\bR\x03has\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count2\xd6\x01\n" +
	"\tExtentMap\x12D\n" +
	"\x05Apply\x12\x1c.silo.extent.v1.ApplyRequest\x1a\x1d.silo.extent.v1.ApplyResponse\x12@\n" +
	"\x03Get\x12\x1a.silo.extent.v1.GetRequest\x1a\x1b.silo.extent.v1.GetResponse0\x01\x12A\n" +
	"\x04Stat\x12\x1b.silo.extent.v1.StatRequest\x1a\x1c.silo.extent.v1.StatResponseB=Z;github.com/hyperized/silo/api/proto/silo/extent/v1;extentv1b\x06proto3"

var (
	file_silo_extent_v1_extent_proto_rawDescOnce sync.Once
	file_silo_extent_v1_extent_proto_rawDescData []byte
)

func file_silo_extent_v1_extent_proto_rawDescGZIP() []byte {
	file_silo_extent_v1_extent_proto_rawDescOnce.Do(func() {
		file_silo_extent_v1_extent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_silo_extent_v1_extent_proto_rawDesc), len(file_silo_extent_v1_extent_proto_rawDesc)))
	})
	return file_silo_extent_v1_extent_proto_rawDescData
}

var file_silo_extent_v1_extent_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_silo_extent_v1_extent_proto_goTypes = []any{
	(*Hlc)(nil),           // 0: silo.extent.v1.Hlc
	(*ExtentEntry)(nil),   // 1: silo.extent.v1.ExtentEntry
	(*ApplyRequest)(nil),  // 2: silo.extent.v1.ApplyRequest
	(*ApplyResponse)(nil), // 3: silo.extent.v1.ApplyResponse
	(*GetRequest)(nil),    // 4: silo.extent.v1.GetRequest
	(*GetResponse)(nil),   // 5: silo.extent.v1.GetResponse
	(*StatRequest)(nil),   // 6: silo.extent.v1.StatRequest
	(*StatResponse)(nil),  // 7: silo.extent.v1.StatResponse
}
var file_silo_extent_v1_extent_proto_depIdxs = []int32{
	0, // 0: silo.extent.v1.ExtentEntry.ts:type_name -> silo.extent.v1.Hlc
	1, // 1: silo.extent.v1.ApplyRequest.entries:type_name -> silo.extent.v1.ExtentEntry
	1, // 2: silo.extent.v1.GetResponse.entries:type_name -> silo.extent.v1.ExtentEntry
	2, // 3: silo.extent.v1.ExtentMap.Apply:input_type -> silo.extent.v1.ApplyRequest
	4, // 4: silo.extent.v1.ExtentMap.Get:input_type -> silo.extent.v1.GetRequest
	6, // 5: silo.extent.v1.ExtentMap.Stat:input_type -> silo.extent.v1.StatRequest
	3, // 6: silo.extent.v1.ExtentMap.Apply:output_type -> silo.extent.v1.ApplyResponse
	5, // 7: silo.extent.v1.ExtentMap.Get:output_type -> silo.extent.v1.GetResponse
	7, // 8: silo.extent.v1.ExtentMap.Stat:output_type -> silo.extent.v1.StatResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_silo_extent_v1_extent_proto_init() }
func file_silo_extent_v1_extent_proto_init() {
	if File_silo_extent_v1_extent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_silo_extent_v1_extent_proto_rawDesc), len(file_silo_extent_v1_extent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_silo_extent_v1_extent_proto_goTypes,
		DependencyIndexes: file_silo_extent_v1_extent_proto_depIdxs,
		MessageInfos:      file_silo_extent_v1_extent_proto_msgTypes,
	}.Build()
	File_silo_extent_v1_extent_proto = out.File
	file_silo_extent_v1_extent_proto_goTypes = nil
	file_silo_extent_v1_extent_proto_depIdxs = nil
}
