// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: silo/extent/v1/extent.proto

package extentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExtentMap_Apply_FullMethodName  = "/silo.extent.v1.ExtentMap/Apply"
	ExtentMap_Get_FullMethodName    = "/silo.extent.v1.ExtentMap/Get"
	ExtentMap_Stat_FullMethodName   = "/silo.extent.v1.ExtentMap/Stat"
	ExtentMap_Delete_FullMethodName = "/silo.extent.v1.ExtentMap/Delete"
)

// ExtentMapClient is the client API for ExtentMap service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ExtentMap is the silod-side RPC surface for replicating a volume's extent map
// (extent index -> chunk id) to the volume's replica set, out of band from the
// gossiped directory namespace. The map is a per-key last-writer-wins CRDT, so
// every entry carries the HLC at which it was bound and applies convergently.
type ExtentMapClient interface {
	// Apply folds a batch of extent bindings into the receiving node's local map
	// for a volume (the coordinator fans this out to the replica set). With no
	// entries and ensure=true it just creates an empty map (first-attach).
	Apply(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*ApplyResponse, error)
	// Get streams a volume's whole extent map back, in batches, so a serving node
	// that is not a holder can warm its map and a lagging replica can be repaired.
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetResponse], error)
	// Stat reports whether the receiving node holds a volume's map and how many
	// extents it has — the existence/health probe the extent scrubber uses.
	Stat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*StatResponse, error)
	// Delete removes a volume's map from the receiving node (the coordinator fans
	// this out to the replica set when a volume is deleted). Removing an unknown
	// map is success, so the call is idempotent under CSI's at-least-once retries.
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type extentMapClient struct {
	cc grpc.ClientConnInterface
}

func NewExtentMapClient(cc grpc.ClientConnInterface) ExtentMapClient {
	return &extentMapClient{cc}
}

func (c *extentMapClient) Apply(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*ApplyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyResponse)
	err := c.cc.Invoke(ctx, ExtentMap_Apply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extentMapClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ExtentMap_ServiceDesc.Streams[0], ExtentMap_Get_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetRequest, GetResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExtentMap_GetClient = grpc.ServerStreamingClient[GetResponse]

func (c *extentMapClient) Stat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*StatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatResponse)
	err := c.cc.Invoke(ctx, ExtentMap_Stat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extentMapClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, ExtentMap_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExtentMapServer is the server API for ExtentMap service.
// All implementations should embed UnimplementedExtentMapServer
// for forward compatibility.
//
// ExtentMap is the silod-side RPC surface for replicating a volume's extent map
// (extent index -> chunk id) to the volume's replica set, out of band from the
// gossiped directory namespace. The map is a per-key last-writer-wins CRDT, so
// every entry carries the HLC at which it was bound and applies convergently.
type ExtentMapServer interface {
	// Apply folds a batch of extent bindings into the receiving node's local map
	// for a volume (the coordinator fans this out to the replica set). With no
	// entries and ensure=true it just creates an empty map (first-attach).
	Apply(context.Context, *ApplyRequest) (*ApplyResponse, error)
	// Get streams a volume's whole extent map back, in batches, so a serving node
	// that is not a holder can warm its map and a lagging replica can be repaired.
	Get(*GetRequest, grpc.ServerStreamingServer[GetResponse]) error
	// Stat reports whether the receiving node holds a volume's map and how many
	// extents it has — the existence/health probe the extent scrubber uses.
	Stat(context.Context, *StatRequest) (*StatResponse, error)
	// Delete removes a volume's map from the receiving node (the coordinator fans
	// this out to the replica set when a volume is deleted). Removing an unknown
	// map is success, so the call is idempotent under CSI's at-least-once retries.
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
}

// UnimplementedExtentMapServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExtentMapServer struct{}

func (UnimplementedExtentMapServer) Apply(context.Context, *ApplyRequest) (*ApplyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Apply not implemented")
}
func (UnimplementedExtentMapServer) Get(*GetRequest, grpc.ServerStreamingServer[GetResponse]) error {
	return status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedExtentMapServer) Stat(context.Context, *StatRequest) (*StatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stat not implemented")
}
func (UnimplementedExtentMapServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedExtentMapServer) testEmbeddedByValue() {}

// UnsafeExtentMapServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExtentMapServer will
// result in compilation errors.
type UnsafeExtentMapServer interface {
	mustEmbedUnimplementedExtentMapServer()
}

func RegisterExtentMapServer(s grpc.ServiceRegistrar, srv ExtentMapServer) {
	// If the following call panics, it indicates UnimplementedExtentMapServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExtentMap_ServiceDesc, srv)
}

func _ExtentMap_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtentMapServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtentMap_Apply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtentMapServer).Apply(ctx, req.(*ApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExtentMap_Get_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ExtentMapServer).Get(m, &grpc.GenericServerStream[GetRequest, GetResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExtentMap_GetServer = grpc.ServerStreamingServer[GetResponse]

func _ExtentMap_Stat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtentMapServer).Stat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtentMap_Stat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtentMapServer).Stat(ctx, req.(*StatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExtentMap_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtentMapServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtentMap_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtentMapServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExtentMap_ServiceDesc is the grpc.ServiceDesc for ExtentMap service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExtentMap_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "silo.extent.v1.ExtentMap",
	HandlerType: (*ExtentMapServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Apply",
			Handler:    _ExtentMap_Apply_Handler,
		},
		{
			MethodName: "Stat",
			Handler:    _ExtentMap_Stat_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ExtentMap_Delete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Get",
			Handler:       _ExtentMap_Get_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "silo/extent/v1/extent.proto",
}
